"""empty message

Revision ID: a6ac7308a028
Revises: 
Create Date: 2017-08-29 02:17:48.024394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac7308a028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome_categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nome_categoria')
    )
    op.create_table('fabricantes',
    sa.Column('id_fabricante', sa.Integer(), nullable=False),
    sa.Column('nome_fabricante', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_fabricante'),
    sa.UniqueConstraint('nome_fabricante')
    )
    op.create_table('fornecedores',
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('nome_fornecedor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_fornecedor'),
    sa.UniqueConstraint('nome_fornecedor')
    )
    op.create_table('bebidas',
    sa.Column('id_bebida', sa.Integer(), nullable=False),
    sa.Column('nome_bebida', sa.String(), nullable=True),
    sa.Column('teor_alcool', sa.Numeric(), nullable=True),
    sa.Column('ingredientes', sa.Text(), nullable=True),
    sa.Column('max_estoque', sa.Integer(), nullable=True),
    sa.Column('min_estoque', sa.Integer(), nullable=True),
    sa.Column('id_fabricante', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_fabricante'], ['fabricantes.id_fabricante'], ),
    sa.PrimaryKeyConstraint('id_bebida'),
    sa.UniqueConstraint('nome_bebida')
    )
    op.create_table('lotes',
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('id_bebida', sa.Integer(), nullable=True),
    sa.Column('id_fornecedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bebida'], ['bebidas.id_bebida'], ),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id_fornecedor'], ),
    sa.PrimaryKeyConstraint('id_lote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotes')
    op.drop_table('bebidas')
    op.drop_table('fornecedores')
    op.drop_table('fabricantes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
